use_frameworks!

platform :ios, '9.0'

target 'CKNetworking_Example' do
  pod 'CKNetworking', :path => '../'

  target 'CKNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
